name: ala-metabolic-engineering
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - cobra
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - scipy
  - pyyaml
  - pip
  - pip:
    - shap
    - plotly